name: moveo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^13.0.0
  dart_appwrite: ^12.1.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  provider: ^6.0.5
  camera: ^0.10.0+3
  fpdart: ^1.1.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_icon.svg
    - assets/apple_icon.svg
    - assets/github_icon.svg
    - assets/twitter_icon.svg
    - assets/svgs/

  fonts:
    - family: Montserrat
      fonts:
         - asset: fonts/Montserrat-Bold.ttf
           weight: 700
         - asset: fonts/Montserrat-Medium.ttf
           weight: 500
         - asset: fonts/Montserrat-Regular.ttf
           weight: 400
         - asset: fonts/Montserrat-SemiBold.ttf
           weight: 600
